image: fela98/mono-nunit

before_script:
  - apt-get install -y tree
  - nuget restore -NonInteractive
  - nuget install MSBuildTasks -Version 1.5.0.235

stages:
  - build

build:
  stage: build
  script:
    #Build DLLs
    - xbuild Build.proj /p:Configuration=Debug /p:Platform="Any CPU" /p:build_number=1.0.0.20
    #Write Config File from Environment Variables
    - echo "UserIdOrEmail:"$UserIdOrEmail > "Consolidated Unit Tests/bin/Debug/Test Documents/MessageData.txt"
    - echo "Password:"$Password >> "Consolidated Unit Tests/bin/Debug/Test Documents/MessageData.txt"
    - echo "ToAddress:"$ToAddress >> "Consolidated Unit Tests/bin/Debug/Test Documents/MessageData.txt"
    - echo "FromAddress:"$FromAddress >> "Consolidated Unit Tests/bin/Debug/Test Documents/MessageData.txt"
    - cat "Consolidated Unit Tests/bin/Debug/Test Documents/MessageData.txt"
    #Change directory and run unit tests
    - cd "Consolidated Unit Tests/bin/Debug"
    - nunit "Consolidated Unit Tests.dll"
    #Build DLLs in Release mode
    - cd ../../../
    - xbuild Build.proj /p:Configuration=Release /p:Platform="Any CPU" /p:build_number=1.0.0.20
  artifacts:
    paths:
      - "Consolidated Unit Tests/bin/Debug/TestResult.xml"
      - "Messaging Library/bin/Release/Messaging Library.dll"