image: fela98/mono-nunit

before_script:
  - apt-get install -y tree
  - nuget restore -NonInteractive

stages:
  - build

build:
  stage: build
  script:
    #Build DLLs
    - xbuild "REST Messaging Projects.sln" /t:Build /p:Configuration=Debug;Platform="Any CPU"
    #Write Config File from Environment Variables
    - echo "UserIdOrEmail:"$UserIdOrEmail > "Consolidated Unit Tests/bin/Debug/Test Documents/MessageData.txt"
    - echo "Password:"$Password >> "Consolidated Unit Tests/bin/Debug/Test Documents/MessageData.txt"
    - echo "ToAddress:"$ToAddress >> "Consolidated Unit Tests/bin/Debug/Test Documents/MessageData.txt"
    - echo "FromAddress:"$FromAddress >> "Consolidated Unit Tests/bin/Debug/Test Documents/MessageData.txt"
    - cat "Consolidated Unit Tests/bin/Debug/Test Documents/MessageData.txt"
    #Change directory and run unit tests
    - cd "Consolidated Unit Tests/bin/Debug"
    - nunit "Consolidated Unit Tests.dll"
    #Build DLLs in Release mode
    - cd ../../../
    - xbuild "REST Messaging Projects.sln" /t:Build /p:Configuration=Release;Platform="Any CPU";AssemblyMajorVersion=1;AssemblyMinorVersion=0;AssemblyBuildNumber=0;AssemblyRevision=20
  artifacts:
    paths:
      - "Consolidated Unit Tests/bin/Debug/TestResult.xml"
      - "Messaging Library/bin/Release/Messaging Library.dll"