image: fela98/mono-nunit

before_script:
  - nuget restore -NonInteractive

stages:
  - build

build:
  stage: build
  script:
    - xbuild "REST Messaging Projects.sln" /t:Build /p:Configuration=Debug;Platform="Any CPU"
    - cd "Consolidated Unit Tests/bin/Debug"
    - nunit "Consolidated Unit Tests.dll"
  artifacts:
    paths:
      - TestResult.txt