image: didstopia/msbuild

# place project specific paths in variables to make the rest of the script more generic
variables:
  DLL_RELEASE_FOLDER: 'Messaging Library\bin\Release'
  TEST_FOLDER: 'Consolidated Unit Tests\bin\Release'
  base_project: 'Messaging Library'
  test_project: 'Consolidated Unit Tests'
  
before_script:
  - apt-get install -y nunit nunit-console
  - nuget restore -NonInteractive

stages:
  - build
  - test

build:
  stage: build
  script:
    #- nuget restore
    #- cd "$base_project"
    - msbuild.exe /p:Configuration=Release,OutputPath=..\build
  artifacts:
    paths:
      - '..\build\Messaging Library.dll'

test:
  stage: test
  script:
    #- nuget restore
    #- cd "$test_project"
    #- msbuild.exe /p:Configuration=Release
    - 'nunit-console "..\build\Consolidated Unit Tests.dll" /out:TestResult.txt'
  artifacts:
    paths:
      - '..\build\TestResult.xml'
  dependencies:
    - build