image: fela98/mono-nunit

before_script:
  - nuget restore -NonInteractive

stages:
  - build

build:
  stage: build
  script:
    #Build DLLs
    - xbuild "REST Messaging Projects.sln" /t:Build /p:Configuration=Debug;Platform="Any CPU"
    #Write Config File from Environment Variables
    - echo "UserIdOrEmail:"$UserIdOrEmail > "Consolidated Unit Tests/bin/Debug/MessageData.txt"
    - echo "Password:"$Password >> "Consolidated Unit Tests/bin/Debug/MessageData.txt"
    - echo "ToAddress:"$ToAddress >> "Consolidated Unit Tests/bin/Debug/MessageData.txt"
    - line "FromAddress:"$FromAddress >> "Consolidated Unit Tests/bin/Debug/MessageData.txt"
    - cat "Consolidated Unit Tests/bin/Debug/MessageData.txt"
    #Change directory and run unit tests
    - cd "Consolidated Unit Tests/bin/Debug"
    - nunit "Consolidated Unit Tests.dll"
  artifacts:
    paths:
      - TestResult.txt